CREATE DATABASE DEPARTMENTS
USE DEPARTMENTS

CREATE TABLE ISCI(
MKOD INT,
ID INT PRIMARY KEY IDENTITY,
VezifeID INT,
SAA NVARCHAR(100),
SALARY FLOAT
)

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(50)
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(100)
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100),
APRICE FLOAT,
SPRICE FLOAT
)

CREATE TABLE SELL(
ID INT PRIMARY KEY IDENTITY,
MehsulID INT REFERENCES MEHSUL(ID),
IsciID INT REFERENCES ISCI(ID),
SALE FLOAT,
SoldDATE DATE DEFAULT GETDATE()
)

SELECT COUNT(SAA) 'Iscilerin Sayi' FROM ISCI

SELECT * FROM ISCI
ORDER BY SALARY DESC

SELECT * FROM MEHSUL
ORDER BY SPRICE DESC

SELECT * FROM SELL
ORDER BY SoldDATE 

SELECT SAA FROM ISCI
UNION 
SELECT VEZIFE FROM VEZIFE